CREATE TABLE [dbo].[Orden]
(
	[IdOrden] INT NOT NULL IDENTITY(1,1) CONSTRAINT PK_Orden PRIMARY KEY CLUSTERED(IdOrden)
,	CantidadProducto INT NOT NULL
,	Estado VARCHAR(50) NOT NULL
,	IdProducto INT NOT NULL
	CONSTRAINT FK_Producto FOREIGN KEY(IdProducto)
    REFERENCES dbo.Producto(IdProducto)
)
WITH (DATA_COMPRESSION = PAGE)
GO